### ISSUE TITLE
Misuse of assumeXXX tests

### ISSUE THREAD

**Issue by mikera** [datacraft-dsc/starfish-java#100]
In many tests,`assumeXXX` methods are being used inappropriately, e.g. in the test class `QueryProvenance_15`:

```
        Assume.assumeNotNull(assetUrl.getMetadata().get("provenance"));
        Map<String, Object> provData = JSON.toMap(assetUrl.getMetadata().get("provenance").toString());

        Assume.assumeNotNull(provData.get("activity"));
        Assume.assumeNotNull(provData.get("wasGeneratedBy"));
```

In all such cases:
- These should be `assertXXX` instead of `assumeXXX`
- The tests should test for the correct value, not simply assert they are not null

**Comment by AyushVerma2** [comment]
Fixed in develop branch,
link: https://github.com/DEX-Company/starfish-java/pull/103

**Comment by mikera** [comment]
@AyushVerma2 please do this *everywhere* not just the example provided.

Unless you actually intend to skip tests, you should never use `assumeXXX`

**Comment by AyushVerma2** [comment]
ok, sure I will review and do for other test case too.

**Comment by AyushVerma2** [comment]
Refactored the test cases, removed the misuse of Assume in test case validation.
