### ISSUE TITLE
Performance of Unit testcases and Integration testcases

### ISSUE THREAD

**Issue by AyushVerma2** [datacraft-dsc/starfish-java#11]
Performance of Unit testcases and Integration testcases

**Comment by mikera** [comment]
Hi, can you be more specific?

I think a reasonable goal is for unit tests to run in <2sec since we don't have anything compute or IO heavy in starfish-java

**Comment by AyushVerma2** [comment]
Hi Mike ,
Kindly review and close.
updated the Pom 
Now the UT is running <4 sec (mvn clean install)
For IT, if the server is not up, it will give a proper message:
"Skipping integration test as Server (uri='http://localhost:8090) is not reachable."

**Comment by mikera** [comment]
Hi I like the performance of the unit tests, this is good.

Two extra things:

1. Can you clear out the warning? I am currently getting somethings like:
```
[WARNING]
[WARNING] Some problems were encountered while building the effective model for sg.dex:starfish-java:jar:0.6.1-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:build-helper-maven-plugin is missing. @ line 248, column 21
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:versions-maven-plugin is missing. @ line 273, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
```

2. Make the interation tests fail if the endpoint is not reachable

**Comment by AyushVerma2** [comment]
I have fixed the point mention above. kindly review.

**Comment by mikera** [comment]
In Beijing right now but please proceed. Assuming it builds cleanly without warning, all is good.
