### ISSUE TITLE
Migrate integration tests to herokuapp

### ISSUE THREAD

**Issue by ilyabukalov** [datacraft-dsc/starfish-java#120]

**Comment by ilyabukalov** [comment]
Reproduced since https://github.com/DEX-Company/starfish-java/commit/9613cf263a53e374a61cd175223cde09b95b0cf9
The correct configuration in properties file are (I have checked and it works):
surfer.host = https://dex-surfer-dev.herokuapp.com
surfer.port = 443
(don't add additional slashes or quotes please otherwise it generates incorrect URL)
Otherwise our initial idea with continuous integration does not work.
If to change these values to correct in config - several integration tests are failed 
It seems they still have hardcoded dependency from back-end side or new herokuapp does not support several features?

**Comment by AyushVerma2** [comment]
Fixed. in latest build

**Comment by ilyabukalov** [comment]
Thanks. it works now 
https://github.com/DEX-Company/starfish-java/commit/83c7720b5d43af82e465844d94df6efbbf43aadc
