### ISSUE TITLE
SF 1.0: Support of DefaultResolver

### ISSUE THREAD

**Issue by AyushVerma2** [datacraft-dsc/starfish-java#140]
SF should support of DefaultResolver, so if the user of starfish has not provided any config file, then starfish should be pointing to default network(currently to Nile network).

**Comment by ilyabukalov** [comment]
https://github.com/DEX-Company/starfish-java/commit/fc7987ad6c5adb8bed358eb22d06d26423c709c6

**Comment by ilyabukalov** [comment]
Done
