### ISSUE TITLE
If the DID is did:dex:XXXXX ,DexResolver throw exception

### ISSUE THREAD

**Issue by AyushVerma2** [datacraft-dsc/starfish-java#150]
sg.dex.starfish.exception.ResolverException: com.oceanprotocol.squid.exceptions.DIDFormatException: Invalid DID Format, it should starts by did:op:

**Comment by ilyabukalov** [comment]
https://github.com/DEX-Company/starfish-java/commit/83853ea65a1d6848dbfbd7cb961a0a431c3f5351
