### ISSUE TITLE
Resolving/Provenance

### ISSUE THREAD

**Issue by ilyabukalov** [datacraft-dsc/starfish-java#155]
These tasks are all related. Description below. The decisions and agreement have been made after discussion with @AyushVerma2

**Comment by ilyabukalov** [comment]
1. To rename resolver to something more general since it will work transparently the same way as with DID->DDO resolving as with AssetID registration. Interface of Resolver will not be changed, only renaming to something "ImmutableLedger" since resolving agents is only part of its functionality.
2. To create separated smart contract for that (actually inheriting ocean codebase) and deploy it to nile network permanently. User input should be the string (by analogy with ocean resolver) which could be DDO or anything else, timestamp is also recorded internally in smart contract and can be obtained later.
4. @pedrorgirardi  By analogy with StatusAPI of Resolving DDO (since interface is the same) it should use as well one more url "/assetID" or "/assetProv" which will return timestamp. StatusAPI will check whether asset was really registered on chain and return this status to user. 
5. @pedrorgirardi in MetaAPI , in surfer, to call internally this new starfish interface after asset hash generation but before returning it to user. It will require the same default config which we recently implemented in starfish but **this config should be moved to surfer side** @AyushVerma2 @pedrorgirardi @mikera . Since many different surfers should have different account in blockchain to control their access rights to blockchain differently.
6. Resolver formal ocean dependencies will be finally removed after this step which gives flexibility to restructure starfish library. After this step we will never call any ocean stuff (including ocean registry smart contract) unless it is related to ocean type asset.
7. Provenance is still stored in meta data.

**Comment by mikera** [comment]
> 1. To rename resolver to something more general since it will work transparently the same way as with DID->DDO resolving as with AssetID registration. Interface of Resolver will not be changed, only renaming to something "ImmutableLedger" since resolving agents is only part of its functionality.

Please keep the name Resolver, as this is consistent with the W3C DID standard. I assume you are familiar with https://w3c-ccg.github.io/did-resolution/ ? We don't need to support this full spec, only the Create / Read / Update DID -> DDO parts right now

**Comment by mikera** [comment]
> 2. To create separated smart contract for that (actually inheriting ocean codebase) and deploy it to nile network permanently. User input should be the string (by analogy with ocean resolver) which could be DDO or anything else, timestamp is also recorded internally in smart contract and can be obtained later.

Our Resolver standard (DEP22) must specify what is expected to be stored (i.e. Valid DDOs). It is OK if the smart contract itself allows arbitrary strings, but the Resolver in starfish should support valid DDOs only.

We probably need a starfish function call to get the timestamp from the resolver, in a Resolver-neutral way. Can you clarify what timestamp is used? Is this compatible with W3C Resolver spec?

**Comment by mikera** [comment]
I think we need to separate Resolver functionality from Provenance.
- DIDs are **per agent**
- Provenance is **per asset**, possibly many for a single Agent DID

**Comment by mikera** [comment]
> @pedrorgirardi By analogy with StatusAPI of Resolving DDO (since interface is the same) it should use as well one more url "/assetID" or "/assetProv" which will return timestamp. StatusAPI will check whether asset was really registered on chain and return this status to user.
> @pedrorgirardi in MetaAPI , in surfer, to call internally this new starfish interface after asset hash generation but before returning it to user. It will require the same default config which we recently implemented in starfish but this config should be moved to surfer side @AyushVerma2 @pedrorgirardi @mikera . Since many different surfers should have different account in blockchain to control their access rights to blockchain differently.

Accessing the asset provenance is presumably just using the Meta API.

Verifying provenance on-chain seems like it should be a starfish capability that can be executed by the client, not something that is delegated to surfer.

**Comment by mikera** [comment]
> Resolver formal ocean dependencies will be finally removed after this step which gives flexibility to restructure starfish library. After this step we will never call any ocean stuff (including ocean registry smart contract) unless it is related to ocean type asset.
> Provenance is still stored in meta data.

Sounds good to me!

**Comment by ilyabukalov** [comment]
> Please keep the name Resolver, as this is consistent with the W3C DID standard. I assume you are familiar with https://w3c-ccg.github.io/did-resolution/ ? We don't need to support this full spec, only the Create / Read / Update DID -> DDO parts right now

ok. I will not mix the things. Actually it does not contradict my points about future development. So, I will create one more interface then specially for provenance. And smart contract need to be created anyway. And yes, all Create / Read / Update DID currently supported by Resolver

**Comment by ilyabukalov** [comment]
> Our Resolver standard (DEP22) must specify what is expected to be stored (i.e. Valid DDOs). It is OK if the smart contract itself allows arbitrary strings, but the Resolver in starfish should support valid DDOs only.

Created separated task for this.
https://github.com/DEX-Company/starfish-java/issues/157

**Comment by ilyabukalov** [comment]
> We probably need a starfish function call to get the timestamp from the resolver, in a Resolver-neutral way. Can you clarify what timestamp is used? Is this compatible with W3C Resolver spec?

1. I can include system timestamp as "current block timestamp as seconds since unix epoch"
2. Then interface extension will be needed, something like getTimestamp(DID did) function in resolver
3. It can be compatible in a sense of getting/resolving appropriate version of DID document depending on the input timestamp parameter. This is currently not supported in Ocean implementation, they simply overwrite always to newer document version. So some development on smart contract side is needed but it is possible. So resolving interface should be changed then to getDDO(DID did, optional timestamp).

**Comment by ilyabukalov** [comment]
> I think we need to separate Resolver functionality from Provenance.
> 
> * DIDs are **per agent**
> * Provenance is **per asset**, possibly many for a single Agent DID

no problem with that. It does not contradict initial idea, it just matter of high level interfaces.

**Comment by ilyabukalov** [comment]
> Verifying provenance on-chain seems like it should be a starfish capability that can be executed by the client, not something that is delegated to surfer.

I just was offering one possible way of use starfish as library by surfer. But of course initially it is part of starfish itself and can be used by user alone as well.

But please look at my point about configuration. I still think that configuration should be externally of starfish. Yes, we provide default config just for simplicity but each one user (or service, let say surfer) has to create its own account for resolving/provenance. Especially if it comes to writes in smart contract. In case of resolver "write" means registering DID, in case of provenance it means registering new assedID. This is described [here](https://github.com/DEX-Company/DEPs/tree/master/22)

**Comment by mikera** [comment]
@ilyabukalov I think this task is too large in scope and should be broken down into individual items that can be addressed / completed independently. It's OK if one depends upon another (can link the issues). Can you do this?

**Comment by ilyabukalov** [comment]
These are
https://github.com/DEX-Company/starfish-java/issues/163
https://github.com/DEX-Company/dex-chain/issues/1
https://github.com/DEX-Company/dex-chain/issues/3
https://github.com/DEX-Company/dex-chain/issues/4
https://github.com/DEX-Company/dex-chain/issues/5
https://github.com/DEX-Company/starfish-java/issues/156
For a while everything, (including design as well) is clear for me.
Assuming this task should be closed
