### ISSUE TITLE
Starfish-java needs release tags for all releases.

### ISSUE THREAD

**Issue by shark8me** [datacraft-dsc/starfish-java#27]
Projects upstream of Starfish-java (e.g. Koi-clj, Starfish-clj etc), sometimes need to replicate issues in a specific version of Starfish-java (e.g. 0.6.0). 
This needs Starfish-java to make release tags for each release, so that the fix can be tested in that release (as opposed to HEAD, which might have changed). Currently no release tags exist. 

In future, please tag all releases of Starfish-java.

**Comment by mikera** [comment]
Not done a release recently, but will for starfish-java 0.6.1 (hopefully today!)
