### ISSUE TITLE
Fix java docs issue

### ISSUE THREAD

**Issue by AyushVerma2** [datacraft-dsc/starfish-java#4]
java docs link should have latest docs, project version

**Comment by mikera** [comment]
@ervintwj something to integrate with the developer site

**Comment by AyushVerma2** [comment]
I have created gh-pages as suggested by Kiran. Kindly review and let me know if it is ok.
Link:
https://dex-company.github.io/starfish-java/

**Comment by mikera** [comment]
It looks OK in general as a framework. Pretty standard JavaDoc setup. Is this now building automatically?

On the first page specifically, I think there should be some overview test and the packages need descriptions (see e.g. https://docs.oracle.com/en/java/javase/11/docs/api/index.html)

Also we need to read through all the public API methods and ask:
- Should this really be public or hidden as an implementation detail?
- Is the description clear and accurate?

**Comment by mikera** [comment]
Is this now building automatically? What do you want me to review and test?

**Comment by AyushVerma2** [comment]
done
