### ISSUE TITLE
Expected Asset ID looks the same but throws a validation exception 

### ISSUE THREAD

**Issue by shark8me** [datacraft-dsc/starfish-java#41]
Running integration test with Starfish-clj's `lein test :only integration.surfer-test` fails with the following exception.

The asset IDs look visually similar but are not.

The problem is only observed with starfish-java 0.7.0 and not with 0.7.1-SNAPSHOT version. Therefore it is already fixed, but Starfish-java needs a new a release for downstream (Starfish-clj, koi-clj) libraries

--
ERROR in (register-with-surfer) (RemoteAgent.java:351)
Uncaught exception, not in assertion.
expected: nil
actual: sg.dex.starfish.exception.StarfishValidationException: Expected asset ID: 1a791d9a7b5ea5a3b9ce1849937a23b79078d79496134928d7580ce7f40f544a but got metadata with hash: 1a791d9a7b5ea5a3b9ce1849937a23b79078d79496134928d7580ce7f40f544a
at sg.dex.starfish.impl.remote.RemoteAgent.getAsset (RemoteAgent.java:351)
sg.dex.starfish.impl.remote.RemoteAgent.createRemoteAsset (RemoteAgent.java:255)
sg.dex.starfish.impl.remote.RemoteAgent.registerRemoteAsset (RemoteAgent.java:231)
sg.dex.starfish.impl.remote.RemoteAgent.registerAsset (RemoteAgent.java:222)
starfish.core$register.invokeStatic (core.cljc:373)
starfish.core$register.invoke (core.cljc:370)
integration.test_surfer$fn__808$fn__809.invoke (test_surfer.clj:22)
integration.test_surfer$fn__808.invokeStatic (test_surfer.clj:19)
integration.test_surfer/fn (test_surfer.clj:18)
clojure.test$test_var$fn__9737.invoke (test.clj:717)
clojure.test$test_var.invokeStatic (test.clj:717)
clojure.test$test_var.invoke (test.clj:708)
clojure.test$test_vars$fn__9763$fn__9768.invoke (test.clj:735)
clojure.test$default_fixture.invokeStatic (test.clj:687)
clojure.test$default_fixture.invoke (test.clj:683)
clojure.test$test_vars$fn__9763.invoke (test.clj:735)
clojure.test$default_fixture.invokeStatic (test.clj:687)
clojure.test$default_fixture.invoke (test.clj:683)
clojure.test$test_vars.invokeStatic (test.clj:731)
clojure.test$test_all_vars.invokeStatic (test.clj:737)
clojure.test$test_ns.invokeStatic (test.clj:758)
clojure.test$test_ns.invoke (test.clj:743)
user$eval224$fn__345.invoke (form-init910697969203306422.clj:1)
clojure.lang.AFn.applyToHelper (AFn.java:156)
clojure.lang.AFn.applyTo (AFn.java:144)
clojure.core$apply.invokeStatic (core.clj:667)
clojure.core$apply.invoke (core.clj:660)
leiningen.core.injected$compose_hooks$fn__154.doInvoke (form-init910697969203306422.clj:1)
clojure.lang.RestFn.applyTo (RestFn.java:137)
clojure.core$apply.invokeStatic (core.clj:665)
clojure.core$apply.invoke (core.clj:660)
leiningen.core.injected$run_hooks.invokeStatic (form-init910697969203306422.clj:1)
leiningen.core.injected$run_hooks.invoke (form-init910697969203306422.clj:1)
leiningen.core.injected$prepare_for_hooks$fn__159$fn__160.doInvoke (form-init910697969203306422.clj:1)
clojure.lang.RestFn.applyTo (RestFn.java:137)
clojure.lang.AFunction$1.doInvoke (AFunction.java:31)
clojure.lang.RestFn.invoke (RestFn.java:408)
clojure.core$map$fn__5866.invoke (core.clj:2755)
clojure.lang.LazySeq.sval (LazySeq.java:42)
clojure.lang.LazySeq.seq (LazySeq.java:51)
clojure.lang.Cons.next (Cons.java:39)
clojure.lang.RT.boundedLength (RT.java:1792)
clojure.lang.RestFn.applyTo (RestFn.java:130)
clojure.core$apply.invokeStatic (core.clj:667)
clojure.test$run_tests.invokeStatic (test.clj:768)
clojure.test$run_tests.doInvoke (test.clj:768)
clojure.lang.RestFn.applyTo (RestFn.java:137)
clojure.core$apply.invokeStatic (core.clj:665)
clojure.core$apply.invoke (core.clj:660)
user$eval224$fn__357$fn__410.invoke (form-init910697969203306422.clj:1)
user$eval224$fn__357$fn__358.invoke (form-init910697969203306422.clj:1)
user$eval224$fn__357.invoke (form-init910697969203306422.clj:1)
user$eval224.invokeStatic (form-init910697969203306422.clj:1)
user$eval224.invoke (form-init910697969203306422.clj:1)
clojure.lang.Compiler.eval (Compiler.java:7177)
clojure.lang.Compiler.eval (Compiler.java:7167)
clojure.lang.Compiler.load (Compiler.java:7636)
clojure.lang.Compiler.loadFile (Compiler.java:7574)
clojure.main$load_script.invokeStatic (main.clj:475)
clojure.main$init_opt.invokeStatic (main.clj:477)
clojure.main$init_opt.invoke (main.clj:477)
clojure.main$initialize.invokeStatic (main.clj:508)
clojure.main$null_opt.invokeStatic (main.clj:542)
clojure.main$null_opt.invoke (main.clj:539)
clojure.main$main.invokeStatic (main.clj:664)
clojure.main$main.doInvoke (main.clj:616)
clojure.lang.RestFn.applyTo (RestFn.java:137)
clojure.lang.Var.applyTo (Var.java:705)
clojure.main.main (main.java:40)

Ran 2 tests containing 2 assertions.
0 failures, 2 errors.
Tests failed.

**Comment by mikera** [comment]
@AyushVerma2 @shark8me let me know when everything is stable and I will do a 0.8.0 release to central

**Comment by shark8me** [comment]
Perhaps we could do a patch release, since this is a minor fix but is a
blocker. Also concerned that this project is already at 0.7.0 , and not
much room till 1.0.0, so patch releases should be the norm, let's reserve
minor release versions for big features.

**Comment by mikera** [comment]
Well, usual convention is 0.17.0 etc... up until version 1.0.0.

I'll do a quick patch release now.

**Comment by mikera** [comment]
@shark8me @AyushVerma2 is this all fixed now? If so please close, thanks!

**Comment by shark8me** [comment]
Not observed now, hence closing
