### ISSUE TITLE
Refactor memory assets to extend AMemoryAsset

### ISSUE THREAD

**Issue by mikera** [datacraft-dsc/starfish-java#50]
All memory assets (MemoryBundle, MemoryAsset etc.) should extend the common base class AMemoryAsset.

Should include following functionality:
- Reference to MemoryAgent
- DIDs derived from MemoryAgent

**Comment by AyushVerma2** [comment]
code merged in PR:
https://github.com/DEX-Company/starfish-java/pull/55
