### ISSUE TITLE
Refactor all Agents to use "Resolver" instead of "Ocean"

### ISSUE THREAD

**Issue by mikera** [datacraft-dsc/starfish-java#51]
Agents should keep a reference to a Resolver, not an Ocean instance.

This is part of the work to separate the Ocean / Squid implementation from the abstract starfish code

**Comment by ilyabukalov** [comment]
https://github.com/DEX-Company/starfish-java/commit/df24bdc4f129e33ec7d6121012db66db007c3e20

**Comment by ilyabukalov** [comment]
https://github.com/DEX-Company/starfish-java/commit/dbd2b0afc32c2b8c4e405729935b2bcc8177e834
