### ISSUE TITLE
Fix Unit Tests / Integration Tests split

### ISSUE THREAD

**Issue by mikera** [datacraft-dsc/starfish-java#69]
I have temporarily moved the integration tests out of `src/test/java` because it is breaking unit test execution with JUnit (as executed in Eclispe).

@AyushVerma2 please find a good solution for this.
1. JUnit / `mvn test` should run *unit tests only*
2. `mvn integration-test` should run *integration tests only*
3. `mvn all-tests` should run all tests
4. Travis CI should run all tests in correct integration context

**Comment by AyushVerma2** [comment]
mvn clean install -P integration-test
-run only Integration test(IT)

mvn clean install -P all-test
- run UT and IT ,also generate javadocs

mvn test
 - run only unit test(UT)

Also Travis CI will run all tests incorrect integration context.
**Currently the Squid Integration test cases is ignored as the Squid config is not stable.

**Comment by mikera** [comment]
Hi @AyushVerma2 can you demo this to me, would like to understand how it is set up before closing
