### ISSUE TITLE
getAsset method args doesn't accept an auth token argument

### ISSUE THREAD

**Issue by shark8me** [datacraft-dsc/starfish-java#71]
In invoke flows, an operation can request an agent for an asset (content or metadata), and provide an auth token.
However RemoteAgent.java does not appear to support passing the token as an argument.

As an  implementation note, RemoteAgent always tries to log in with Basic Auth, gets the token, and then proceeds on the rest of the request. This is wasteful. If a token is passed an argument, that would avoid an addition create-token request.

**Comment by mikera** [comment]
You should be able to create a RemoteAgent with a RemoteAccount, where the RemoteAccount contains the credentials. @AyushVerma2 can you help Kiran to make this work?

**Comment by AyushVerma2** [comment]
@shark8me: As discussed today, I have fixed this and written test case for the same.
1.test RemoteAccount creation using the credential
2.test RemoteAccount creation using the token
New test case class created: RemoteAgentTest_26.java.
Let me know if you have any further issue.
Kindly review and close the issue if it is fixed.

**Comment by shark8me** [comment]
@AyushVerma2 I presume that the PR for this is already merged? If so, please go ahead and resolve this.

**Comment by AyushVerma2** [comment]
yes the PR is merged last week, so closing the issue.
