### ISSUE TITLE
getDID() not working from RemoteOperation

### ISSUE THREAD

**Issue by mikera** [datacraft-dsc/starfish-java#79]
When trying to use getDID on a RemoteOperation I get this error

```
Execution error (UnsupportedOperationException) at sg.dex.starfish.impl.AAsset/getDID (AAsset.java:55).
Unable to obtain DID for asset of class: class sg.dex.starfish.impl.remote.RemoteOperation
```

getDID must work for any type of remote asset. Please add tests to validate this.

**Comment by ilyabukalov** [comment]
https://github.com/DEX-Company/starfish-java/pull/119

**Comment by ilyabukalov** [comment]
https://github.com/DEX-Company/starfish-java/commit/584164c3b4afa25476f1303b5c856fbddb1b5d16
