### ISSUE TITLE
Null pointer exception in RemoteAgent invoke

### ISSUE THREAD

**Issue by mikera** [datacraft-dsc/starfish-java#80]
Failure with this error when attempting a remote invoke:

```
Caused by: java.lang.NullPointerException
	at sg.dex.starfish.impl.remote.RemoteAgent.isModeSupported(RemoteAgent.java:831)
	at sg.dex.starfish.impl.remote.RemoteAgent.invokeResult(RemoteAgent.java:796)
	at sg.dex.starfish.impl.remote.RemoteOperation.invokeResult(RemoteOperation.java:50)
	....
```

invoke should not fail with this kind of error. Should probably assume that a mode can be supported and attempt the invoke as normal if modes are not specified in the metadata. Please also update DEP6 to reflect appropriate behaviour / logic if needed

**Comment by AyushVerma2** [comment]
@mikera: let me know if the below check for mode is ok?
1. If mode is not present in Operation metadata.
   - Default mode will be Async (will update the DEP6)
2. If invalid mode is present:
  - Default mode will be Async (will update the DEP6)
3. If Only Async mode is present and the user tries to call Sync operation or vice -versa
  - The exception will be thrown, stating mode is not supported or do we need to proceed with
      default mode?
4. Any other check?

**Comment by mikera** [comment]
1. Default if no mode should always be what the user requests (i.e. what starfish function did they call?)
2. Invoke should fail if mode is present but not valid (bad metadata)
3. I think an exception is correct here, but may need to revisit. It would be possible for a sync call to convert to an async call and just wait for the result, for example. Or an async call could create a local job in a thread and do a sync call in the background.

**Comment by AyushVerma2** [comment]
Fixed in git pull request:
https://github.com/DEX-Company/starfish-java/pull/96

**Comment by mikera** [comment]
@AyushVerma2 can you point me to tests that verify this?

**Comment by AyushVerma2** [comment]
below are the Test cases added in TestMemoryOperations.java class

1. testInvalidMetadata
2. testMetadataWithNoMode
3. testMetadataWithNoMode_Sync
4. testMetadataWithInvalidMode
5. testMetadataWitModeSyncForAsyncCall
6. testMetadataWitModeASyncForSyncCall

**Comment by mikera** [comment]
@AyushVerma2 I don't see any of these methods - which branch / repo are they on? And are these testing the RemoteAgent properly?

**Comment by AyushVerma2** [comment]
@mikera: Sorry it was left unmerged, now it is available in develop branch. 
Currently, I have written test cases for Memory implementation, soon will be writing the same for Remote Operation.
