### ISSUE TITLE
Quality: UT,Integration test,Code coverage

### ISSUE THREAD

**Issue by AyushVerma2** [datacraft-dsc/starfish-java#9]
Quality: 
UT - make sure Unit test case run smoothly every time.
Integration test - if it is failing it should give proper/clear Error message

**Comment by mikera** [comment]
For code coverage, need to ensure that all main code paths are covered. Probably best to make this a separate issue though?

**Comment by mikera** [comment]
Integration test - see my comments on other issue. Should FAIL if integration does not succeed.
